cmake_minimum_required(VERSION 3.1.0)
set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_AUTOMOC ON)

if(CMAKE_VERSION VERSION_LESS "3.7.0")
    set(CMAKE_INCLUDE_CURRENT_DIR ON)
endif()

find_package(Qt5 5.11 COMPONENTS Gui Widgets)

set(QVGUIPLUGIN_INTERFACE_HEADERS
    ${QVPLUGIN_INTERFACE_INCLUDE_DIR}/QvGUIPluginInterface.hpp)

list(APPEND QV2RAY_QT_LIBS Qt5::Gui Qt5::Widgets)
